---
galaxy_info:
  role_name: haproxy
  namespace: tititwister
  author: TitiTwister
  description: HAProxy hostname-based HTTP/TCP reverse proxy and load balancer
  license: Beerware
  min_ansible_version: "2.18"
  platforms:
    - name: EL
      versions: ["9"]
  galaxy_tags: [loadbalancer, networking, proxy]

dependencies: []
